app:
  debug: false
  listen: "0.0.0.0"
  port: 5000
  search_paths:
    - ~/git-server/repos
    - /opt/git-server/repos
  ondemand:
    search_paths:
      - ~/git-server/repos.ondemand
      - /opt/git-server/repos.ondemand
auth:
  users:
    git-user:
      password: git-password  